In [ ]:
# generate data
# list of points
import numpy as np 
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist

np.random.seed(2)

In [14]:
# Tọa độ trung bình (mean) của hai cụm dữ liệu
means = [[2, 2], [4, 2]]
# Ma trận hiệp phương sai (covariance matrix) để tạo dữ liệu phân tán
cov = [[.3, .2], [.2, .3]]
# Số lượng mẫu cho mỗi cụm
N = 10

# Tạo data từ cụm đầu tiên (X0) với tạo độ trung bình means[0] và ma trận hiệp phương sai
X0 = np.random.multivariate_normal(means[0], cov, N).T
# Tạo data từ cụm đầu tiên (X1) với tạo độ trung bình means[1] và ma trận hiệp phương sai
X1 = np.random.multivariate_normal(means[1], cov, N).T

# Ghép dữ liệu từ cả hai cụm thành ma trận X
X = np.concatenate((X0, X1), axis = 1)
# Tạo nhãn labels với nhãn 1 là 1 và nhãn 2 là -1
y = np.concatenate((np.ones((1, N)), -1 * np.ones((1, N))), axis = 1)

# Ouput data
print(f"X0 {X0}")
print(f"X1 {X1}")
print(f"X {X}")
# Xbar
X = np.concatenate((np.ones((1, 2 * N)), X), axis = 0)
print(f"Xbar {X}")

X0 [[1.67657074 2.12880387 2.26908635 1.35082428 1.25536335 1.58672124
  2.05228761 2.61197243 2.84442429 2.87417083]
 [2.63569993 1.75009054 1.6704512  1.51642964 1.65883024 2.02298231
  1.75613874 2.41154256 3.66103384 2.83989658]]
X1 [[5.11172013 4.10924821 3.95711388 4.22448673 3.8182477  4.02136443
  3.93580126 5.17411589 3.84202124 3.4062144 ]
 [2.20584714 1.97299717 2.20261025 2.39388876 1.66850086 2.26215508
  2.00694779 3.2002868  1.78143285 2.2578772 ]]
X [[1.67657074 2.12880387 2.26908635 1.35082428 1.25536335 1.58672124
  2.05228761 2.61197243 2.84442429 2.87417083 5.11172013 4.10924821
  3.95711388 4.22448673 3.8182477  4.02136443 3.93580126 5.17411589
  3.84202124 3.4062144 ]
 [2.63569993 1.75009054 1.6704512  1.51642964 1.65883024 2.02298231
  1.75613874 2.41154256 3.66103384 2.83989658 2.20584714 1.97299717
  2.20261025 2.39388876 1.66850086 2.26215508 2.00694779 3.2002868
  1.78143285 2.2578772 ]]
Xbar [[1.         1.         1.         1.         1.         1.
  1.   

In [15]:
# Hàm tính đầu ra khi biết đầu vào x và weights w
def h(w, x):    
    return np.sign(np.dot(w.T, x))

In [16]:
# Kiểm tra hội tụ. Cần so sánh h(w, X) với ground truth y. Giống nhau thì dừng thuật
def has_converged(X, y, w):    
    return np.array_equal(h(w, X), y) 


In [19]:
# Hàm thực hiện PLA
def perceptron(X, y, w_init):
    w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    mis_points = []
    while True:
        # Mix data
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = X[:, mix_id[i]].reshape(d,1)
            yi = y[0, mix_id[i]]
            if h(w[-1], xi)[0] != yi: # misclassified point
                mis_points.append(mix_id[i])
                w_new = w[-1] + yi * xi
                w.append(w_new)
        if has_converged(X, y, w[-1]):
            break
    return (w, mis_points)
d = X.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = perceptron(X, y, w_init)
w

[array([[-0.71901345],
        [ 0.04057615],
        [-0.44851529]]),
 array([[0.28098655],
        [2.88500044],
        [3.21251855]]),
 array([[-0.71901345],
        [-1.33948628],
        [ 0.81862979]]),
 array([[0.28098655],
        [1.27248615],
        [3.23017235]]),
 array([[-0.71901345],
        [-2.13372826],
        [ 0.97229515]]),
 array([[0.28098655],
        [0.13535809],
        [2.64274635]]),
 array([[-0.71901345],
        [-3.82175579],
        [ 0.4401361 ]]),
 array([[ 0.28098655],
        [-0.94758496],
        [ 3.28003268]]),
 array([[-0.71901345],
        [-5.05683316],
        [ 1.30703551]]),
 array([[ 0.28098655],
        [-3.80146981],
        [ 2.96586576]]),
 array([[ 1.28098655],
        [-0.92729898],
        [ 5.80576233]]),
 array([[ 0.28098655],
        [-5.03654719],
        [ 3.83276517]]),
 array([[ 1.28098655],
        [-2.76746084],
        [ 5.50321637]]),
 array([[ 0.28098655],
        [-6.17367524],
        [ 3.24533917]]),
 array([[ 1.280

In [20]:
m

[8, 13, 7, 19, 2, 12, 9, 11, 4, 9, 11, 2, 19, 8, 16, 1]